 version: '2'
 services:
   web:
     build:
        context: .
     volumes:
       - ./project:/usr/src/project
     expose:
       - "3031"
     command: uwsgi --ini /usr/src/project/web.ini 

   nginx:
     restart: always
     build: ./nginx/
     ports:
       - "80:80"
       - "8080:8080"
     volumes:
       - /www/static
     volumes_from:
       - web
     links:
       - web:web
